/**
 * seed-motivos.mjs
 * Migra los motivos hardcodeados de motivos.js a Firestore (colección 'motivos_tipo').
 * Cada motivo queda con { nombre, visible: true }.
 * 
 * Uso: node scripts/seed-motivos.mjs
 */
import { initializeApp, cert, getApps } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';
import { readFileSync } from 'fs';

const sa = JSON.parse(readFileSync('.secrets/stc-cmms-hilanderia-firebase-adminsdk-fbsvc-5dc94a0016.json', 'utf8'));
if (!getApps().length) initializeApp({ credential: cert(sa), projectId: 'stc-cmms-hilanderia' });
const db = getFirestore();

// ── Motivos origen (copia de motivos.js) ─────────────────────────────────────
const MOTIVOS_POR_TIPO = {
  APERTURA: {
    'Mecánico': ['ATASCO / OBSTRUCCIÓN DUCTO ASPIRACIÓN','ROTURA CORREA TRAPEZOIDAL','DESGASTE PALETA VENTILADOR','FALLA BARRERA DE LUZ','ROTURA CABLE ELEVACIÓN (BO-A)','ROTURA CADENA RODILLOS','AJUSTE TENSIÓN CORREA','DESGASTE TIRA ESTANQUIDAD','ROTURA CADENA TRANSPORTE BALAS','FALLA RODILLO EXTRACTOR','AJUSTE','LIMPIEZA','LUBRICACIÓN','CAMBIO','VERIFICACIÓN'],
    'Eléctrico': ['DISPARO TÉRMICO MOTOR','ERROR VARIADOR','FALLA BARRERA DE LUZ','FALLA MÓDULO MEMORIA / EEPROM','CAMBIO FUSIBLE ARMARIO','CAMBIO PILA ZPB4','FALLA SENSOR PRESENCIA BALA','VERIFICACIÓN ELÉCTRICA','AJUSTE PARÁMETROS'],
  },
  CARDA: {
    'Mecánico': ['ROTURA GUARNICIÓN TAMBOR','DESGASTE CHAPONES','ROTURA CINTA','ATASCO LICKER-IN','ROTURA CORREA DENTADA','DESGASTE GUARNICIÓN DOFFER','FALLA APILADORA CBA','DESAJUSTE GALGA CHAPÓN/TAMBOR','DESGASTE RODILLOS CALANDRA','AJUSTE','LIMPIEZA','LUBRICACIÓN','CAMBIO','VERIFICACIÓN'],
    'Eléctrico': ['ERROR VARIADOR TAMBOR','DISPARO TÉRMICO MOTOR','FALLA AUTOLEVELER','FALLA SENSOR CINTA (ITOR)','ALARMA VELOCIDAD TAMBOR','VERIFICACIÓN ELÉCTRICA','AJUSTE PARÁMETROS'],
  },
  MANUAR: {
    'Mecánico': ['ROTURA DE CINTA','DESGASTE CILINDROS ESTIRAJE','ATASCO DE FIBRA','ROTURA DE CORREA','DESAJUSTE ESTIRAJE','AJUSTE','LIMPIEZA','LUBRICACIÓN','CAMBIO','VERIFICACIÓN'],
    'Eléctrico': ['DISPARO TÉRMICO MOTOR','ERROR DE VARIADOR','FALLA SENSOR PESO CINTA','VERIFICACIÓN ELÉCTRICA','AJUSTE PARÁMETROS'],
  },
  'OPEN END': {
    'Mecánico': ['DESGASTE DE ROTOR','DESGASTE ABERTURA','ATASCO DE FIBRA','ROTURA DE CORREA','FALLA TOBERA','DESGASTE DE COJINETES','AJUSTE','LIMPIEZA','LUBRICACIÓN','CAMBIO','VERIFICACIÓN'],
    'Eléctrico': ['DISPARO TÉRMICO MOTOR','ERROR DE VARIADOR','FALLA SENSOR ROTURA HILO','VERIFICACIÓN ELÉCTRICA','AJUSTE PARÁMETROS'],
  },
  FILTRO: {
    'Mecánico': ['OBSTRUCCIÓN DE FILTRO','ROTURA MANGA FILTRANTE','FUGA DE DUCTO','DESGASTE DE VENTILADOR','AJUSTE','LIMPIEZA','LUBRICACIÓN','CAMBIO','VERIFICACIÓN'],
    'Eléctrico': ['DISPARO TÉRMICO MOTOR','SENSOR DE PRESIÓN','VERIFICACIÓN ELÉCTRICA','AJUSTE PARÁMETROS'],
  },
  URDIDORA: {
    'Mecánico': ['ROTURA DE HILO','FALLA SISTEMA TENSIÓN','DESGASTE DE CILINDROS','DESAJUSTE DE PEINE','ROTURA DE CORREA','AJUSTE','LIMPIEZA','LUBRICACIÓN','CAMBIO','VERIFICACIÓN'],
    'Eléctrico': ['ERROR DE VARIADOR','FALLA SENSOR TENSIÓN','FALLA DE ENCODER','VERIFICACIÓN ELÉCTRICA','AJUSTE PARÁMETROS'],
  },
  INDIGO: {
    'Mecánico': ['FUGA SELLO MECÁNICO','PÉRDIDA DE PRESIÓN','OBSTRUCCIÓN DE FILTRO','FUGA CILINDRO NEUMÁTICO','ROTURA / ALARG. CADENA','DESGASTE GUARNICIÓN FRENO','DESINCRONIZACIÓN CILINDRO','AJUSTE','LIMPIEZA','LUBRICACIÓN','CAMBIO','VERIFICACIÓN'],
    'Eléctrico': ['ERROR DE VARIADOR','ALARMA DE NIVEL','DISPARO TERMOSTATO','ERROR DE ENCODER','FALLA COMUNICACIÓN BUS','SENSOR FUERA DE RANGO','VERIFICACIÓN ELÉCTRICA','AJUSTE PARÁMETROS'],
  },
  TELAR: {
    'Mecánico': ['ROTURA DE URDIMBRE','ROTURA DE TRAMA','DESGASTE DE LEVA','FALLA MECANISMO LIZOS','DESGASTE DE PEINE','FALLA SISTEMA DE FRENO','DESAJUSTE TENSOR','AJUSTE','LIMPIEZA','LUBRICACIÓN','CAMBIO','VERIFICACIÓN'],
    'Eléctrico': ['ERROR DE VARIADOR','FALLA SENSOR TRAMA','FALLA DE ENCODER','DISPARO TÉRMICO MOTOR','VERIFICACIÓN ELÉCTRICA','AJUSTE PARÁMETROS'],
  },
  REVISADORA: {
    'Mecánico': ['ROTURA DE CORREA','DESGASTE DE CILINDROS','FALLA SISTEMA TENSIÓN','AJUSTE','LIMPIEZA','LUBRICACIÓN','CAMBIO','VERIFICACIÓN'],
    'Eléctrico': ['FALLA ILUMINACIÓN','DISPARO TÉRMICO MOTOR','VERIFICACIÓN ELÉCTRICA','AJUSTE PARÁMETROS'],
  },
  MERCERIZADORA: {
    'Mecánico': ['FUGA DE LÍQUIDO','OBSTRUCCIÓN BOQUILLAS','DESGASTE CILINDROS','FALLA BOMBA CIRCULACIÓN','AJUSTE','LIMPIEZA','LUBRICACIÓN','CAMBIO','VERIFICACIÓN'],
    'Eléctrico': ['DISPARO TERMOSTATO','ERROR DE VARIADOR','SENSOR CONCENTRACIÓN','VERIFICACIÓN ELÉCTRICA','AJUSTE PARÁMETROS'],
  },
  INTEGRADA: {
    'Mecánico': ['FUGA SELLO MECÁNICO','OBSTRUCCIÓN DE FILTRO','ROTURA / ALARG. CADENA','DESGASTE CILINDROS','FALLA BOMBA CIRCULACIÓN','AJUSTE','LIMPIEZA','LUBRICACIÓN','CAMBIO','VERIFICACIÓN'],
    'Eléctrico': ['ERROR DE VARIADOR','DISPARO TERMOSTATO','FALLA DE ENCODER','VERIFICACIÓN ELÉCTRICA','AJUSTE PARÁMETROS'],
  },
};

async function seed() {
  let count = 0;
  for (const [tipo, categorias] of Object.entries(MOTIVOS_POR_TIPO)) {
    const data = { tipo };
    for (const [cat, lista] of Object.entries(categorias)) {
      data[cat] = lista.map(nombre => ({ nombre, visible: true }));
    }
    await db.collection('motivos_tipo').doc(tipo).set(data, { merge: false });
    console.log(`✔ ${tipo}: ${Object.values(categorias).flat().length} motivos`);
    count++;
  }
  console.log(`\nListo. ${count} tipos migrados a Firestore.`);
}

seed().catch(console.error);
